PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX bundle: <http://purl.org/net/bundle#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?shelfmark ?item ?manifestation ?bundle ?rvk ?notation
WHERE {
    ?item dct:title ?shelfmark .
    ?item efrbroo:R7_is_example_of ?manifestation .
    OPTIONAL { ?bundle bundle:encapsulates ?manifestation . }
    OPTIONAL { ?bundle dct:subject ?rvk . }
    OPTIONAL { ?rvk skos:notation ?notation . }
    FILTER(regex(str(?shelfmark), "^Sn 123", "i"))
}
ORDER BY ?shelfmark
