PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rvko: <http://data.ub.tu-dortmund.de/resource/rvko/>

SELECT (COUNT(distinct ?work) AS ?cnt) WHERE {
	?work <http://purl.org/net/bundle#encapsulated_in> ?bundle .
    ?bundle dct:subject ?rvk .
    ?rvk skos:broader ?current .
    ?current skos:notation "%s" .
}